Aurorastation/Aurora

- code/game/objects/items/devices/radio/headset.dm
- code/game/objects/items/devices/radio/radio.dm
- code/modules/mob/living/carbon/human/say.dm
- code/modules/paperwork/clipboard.dm
The radio changes will need more thorough testing than I managed by myself on a local server, but all channels + common + arbitrary frequencies + binary worked locally.
> Clipboard fix, completes binary comm port.

- SQL/aurora_schema.sql
- code/controllers/master_controller.dm
- code/game/machinery/requests_console.dm
- code/game/objects/items/weapons/weaponry.dm
- code/modules/admin/IsBanned.dm
- code/modules/admin/verbs/check_customitem_activity.dm
- code/modules/client/preferences_factions.dm
- code/modules/customitems/item_spawning.dm
- code/world.dm
* IP Blacklist Update
* Request Console Improvements
* Start up optimization
* SQL Schema
* Player setup stuff
* Custom item spawning
* Katanas and Claymores are now bulky
> Skull's Things, 21JAN2014

- code/modules/customitems/item_spawning.dm
Now actually checks the character name. A novel ass concept, right?
> Item Spawning Hotfix

- code/controllers/configuration.dm
- code/game/machinery/doors/windowdoor.dm
- code/modules/mob/living/silicon/pai/pai.dm
- code/modules/mob/living/silicon/pai/software.dm
- interface/interface.dm
- interface/skin.dmf
* pAIs can no longer open windoors, at all. Fix for issue #399 
* pAIs now have a better management of being able to translate sign language. Enhancement #405 
* Adds a button for the Github page. Needs a config modification for the variable githuburl
> Skull's Things, 25FEB2015

- code/game/verbs/ooc.dm
- code/modules/mob/living/simple_animal/friendly/mouse.dm
- code/stylesheet.dm
Includes #393 because I forgot the thing.
> Scopes Updates

- code/modules/client/preferences.dm
Because we paint computers, so why not pain IPCs? Also, a bypass already
exists, so might as well make it official.
Body colour is linked to the hair colour, so you'll have a uniform
coating.
> Body Colour for IPCs

- code/game/jobs/job/medical.dm
Title no longer necessary. Leave note to scrutinize pulls better.
> Remove Emergency Physician

- code/game/objects/structures/crates_lockers/closets/secure/medical.dm
Fix for https://github.com/Aurorastation/Aurora/issues/416
Simple oversight on my part. My bad.
Tested and confirmed works.
Signed-off-by: Jamini <mobiousjami@gmail.com>
> Fixing EMT access to medical lockers

- code/game/objects/items/devices/taperecorder.dm
Bringing back Mission impossible
> Taperecorder #513 fixed

- SQL/aurora_schema.sql
- aurora.dme
- code/game/objects/items/stacks/nanopaste.dm
- code/modules/admin/DB ban/functions.dm
- code/modules/admin/IsBanned.dm
- code/modules/admin/admin.dm
- code/modules/admin/player_notes.dm
- code/modules/admin/player_notes_sql.dm
- code/modules/admin/topic.dm
- code/modules/admin/verbs/warning.dm
- code/modules/detectivework/forensics.dm
- nano/templates/dnaforensics.tmpl
* Fixes issue #586 
* Fixes issue #587 
* Adds a few admin-side tweaks, primarily to the notes system.
> Notes and Fixes

- code/modules/admin/player_notes_sql.dm
- code/modules/admin/topic.dm
- code/modules/admin/verbs/warning.dm
* Fixes the dumb with the caller name saving
* Disables the transfer proc
> Fixes for notes

- code/modules/admin/IsBanned.dm
- code/modules/admin/player_notes_sql.dm
- code/modules/admin/topic.dm
Moral of the story: never code when it's late.
> Hotfix 2, 08JUN2015

- code/modules/admin/DB ban/functions.dm
- code/modules/admin/IsBanned.dm
> Autobanner fix 2

- code/modules/reagents/reagent_containers/glass.dm
Increasing the size of large and regular sized beakers to values divisible by 30.
This will make chemistry much easier. 
See this thread: http://aurorastation.org/forums/viewtopic.php?f=18&t=2684
> Beaker Size Revision

- code/__HELPERS/unsorted.dm
- code/modules/organs/synth_skin.dm
I thought I'd open a pull request with fixes for any issues that pop up regarding the IPC stuff. So far there's just this one.
> Bugfixes - IPC

- code/_onclick/ai.dm
This is one of those things that just got overlooked I think.
> Lets AI's lock and unlock emitters

- code/game/objects/items/devices/radio/radio.dm
- code/modules/mob/living/silicon/robot/robot.dm
This also gives cyborgs the ability to control their broadcast radius for normal radio channels.
> Emag syndicate radio

- code/__HELPERS/mobs.dm
- code/game/dna/dna_modifier.dm
- code/game/machinery/Sleeper.dm
- code/game/machinery/adv_med.dm
- code/game/machinery/cryo.dm
- code/game/machinery/cryopod.dm
- code/game/objects/structures/tables_racks.dm
This pull allows people to click and drag nearby people into medical machinery. This does not affect the ability to grab and click.
Devices affected:
* Medical Scanner
* Dna Scanner
* Sleeper
* Cryopod
* Cryo Tube
This also allows robots to put people on tables, which will allow for proper surgery.
This is an enhancement.
> Click and drag medical machinery

- code/modules/mob/dead/observer/observer.dm
- code/modules/mob/living/carbon/brain/posibrain.dm
- code/modules/mob/living/silicon/pai/recruit.dm
Here's this one! Forgot it yesterday.
> No more posibrain / PAI spam

- code/modules/secretsanta/submission_box.dm
Because people have snowflakey names. Grr.
> Secret Santa - SQL Query Fix

- code/modules/secretsanta/submission_box.dm
Everything works now! Also has a function to assign everyone a mark. It will failtrain if you have an uneven amount of people on the database, though.
> Secret santa - Fixes

- code/modules/secretsanta/submission_box.dm
* Assign function fixed, for future use
* More fucking sanitization
Will fail travis because I'm fucking lazy.
> Secret santa - More Fixes

- SQL/aurora_schema.sql
- SQL/feedback_schema.sql
- code/controllers/configuration.dm
- code/defines/procs/dbcore.dm
- code/game/jobs/whitelist.dm
- code/modules/client/client defines.dm
- code/modules/client/client procs.dm
Adds a few new tables, makes using DB queries and variable sanitization easier, and makes the whitelists SQL dependent, if you want to use that option.
> Database updates

- code/defines/procs/dbcore.dm
- code/game/jobs/whitelist.dm
Fixes two functionality errors that I let into the SQL code as I was redoing/fiddling with it.
> Database Fixes

- code/game/gamemodes/factions.dm
- code/game/gamemodes/game_mode.dm
- code/game/gamemodes/vampire/vampire_powers.dm
- code/game/mecha/medical/odysseus.dm
- code/game/objects/items/stacks/sheets/glass.dm
- code/game/objects/items/weapons/grenades/flashbang.dm
- code/game/objects/items/weapons/implants/implant.dm
- code/game/objects/items/weapons/storage/uplink_kits.dm
- code/modules/detectivework/forensics.dm
- code/modules/mob/living/carbon/human/life.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/silicon/pai/hud.dm
- code/modules/power/power.dm
- code/modules/reagents/reagent_containers/blood_pack.dm
- html/changelog.html
* Fixes the Vaurca damage mechanics
* Makes the Vaurca insulated properly
(Both mentioned in #802 )
* Updates changelog
> Bug fixes jan2016

- SQL/aurora_schema.sql
- code/game/gamemodes/game_mode.dm
Missing tables and a quick hotfix for logging species_statistics.
> Sql updates

- code/modules/research/xenoarchaeology/finds/finds.dm
Xenoarchaeology gun sprite missing.
Issue #801
> Fixes #801

- code/modules/clothing/spacesuits/rig.dm
Disables Vaurca hardsuits, Barring Syndicate suits.
> Fixes #822

- code/game/objects/items/weapons/cigs_lighters.dm
- code/modules/client/preferences_gear.dm
- code/modules/clothing/gloves/color.dm
Adds a number of long-since forgotten custom loadout changes that were
made but never pulled.
> Custom Loadout Additions

- aurora.dme
- code/WorkInProgress/kilakk/fax.dm
- code/controllers/configuration.dm
- code/game/gamemodes/gameticker.dm
- code/modules/admin/permissionverbs/permsission lists.dm
- code/modules/admin/topic.dm
- code/modules/admin/verbs/adminhelp.dm
- code/modules/admin/verbs/pray.dm
- code/modules/aurora/duty_officer/duty officer.dm
- code/modules/ext_scripts/discord.dm
- scripts/discordbot_message.py
Implements the Borealis/Discord bot in a simple form. Currently only serves to forward messages to the specific channels as we go. Also a slight refractor on how faxes work, and how they're stored/managed.
> Borealis bot - Initial Implementation

- SQL/aurora_schema.sql
- code/datums/supplypacks.dm
- code/game/gamemodes/game_mode.dm
- code/game/mecha/mech_fabricator.dm
- code/game/objects/items/weapons/implants/implantcase.dm
- code/game/objects/items/weapons/implants/implanter.dm
- code/modules/mob/living/carbon/human/examine.dm
- code/modules/mob/living/carbon/human/species.dm
- code/modules/mob/living/silicon/robot/component.dm
- code/modules/mob/new_player/new_player.dm
- code/modules/organs/organ_alien.dm
- code/modules/organs/pain.dm
Creates the IPC/Shell tags and implements them into the game.
> IPC/Shell Tagging

- code/modules/aurora/duty_officer/duty officer.dm
> Check_fax_history fix 2

- code/modules/admin/admin_verbs.dm
- code/world.dm
> Fixing Visibility -- Again
